(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var c=this||self;function e(a,l){a=a.split(".");var b=c;a[0]in b||"undefined"==typeof b.execScript||b.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===l?b[d]&&b[d]!==Object.prototype[d]?b=b[d]:b=b[d]={}:b[d]=l}var f=/^[\w+/_-]+[=]{0,2}$/,g=null;function h(a){return(a=a.querySelector&&a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&f.test(a)?a:""}function k(a){return a};var m={0:"Tradueix",1:"Cancel\u00b7la",2:"Tanca",3:function(a){return"Google ha tradu\u00eft autom\u00e0ticament aquesta p\u00e0gina a: "+a},4:function(a){return"Tradu\u00eft a l'idioma: "+a},5:"Error: el servidor no ha pogut completar la sol\u00b7licitud. Torneu-ho a provar m\u00e9s tard.",6:"M\u00e9s informaci\u00f3",7:function(a){return"Tecnologia de "+a},8:"Traductor",9:"Traducci\u00f3 en curs",10:function(a){return"Vols traduir aquesta p\u00e0gina a "+(a+" amb el Traductor de Google?")},11:function(a){return"Mostra aquesta p\u00e0gina en: "+
a},12:"Mostra l'original",13:"El contingut d'aquest fitxer local s'enviar\u00e0 a Google per traduir-lo mitjan\u00e7ant una connexi\u00f3 segura.",14:"El contingut d'aquesta p\u00e0gina segura s'enviar\u00e0 a Google per traduir-lo mitjan\u00e7ant una connexi\u00f3 segura.",15:"El contingut d'aquesta p\u00e0gina d'intranet s'enviar\u00e0 a Google per traduir-lo mitjan\u00e7ant una connexi\u00f3 segura.",16:"Seleccioneu l'idioma",17:function(a){return"Desactiva la traducci\u00f3 del "+a},18:function(a){return"Desactiva per a: "+
a},19:"Amaga sempre",20:"Text original:",21:"Contribu\u00efu a millorar la traducci\u00f3",22:"Contribueix",23:"Tradueix-ho tot",24:"Restaura-ho tot",25:"Cancel\u00b7la-ho tot",26:"Tradueix les seccions al meu idioma",27:function(a){return"Tradueix-ho tot a: "+a},28:"Mostra els idiomes originals",29:"Opcions",30:"Desactiva la traducci\u00f3 per a aquest lloc",31:null,32:"Mostra traduccions alternatives",33:"Feu clic a les paraules que hi ha m\u00e9s amunt per obtenir traduccions alternatives",34:"Fes-lo servir",
35:"Arrossegueu amb la tecla Maj per canviar l'ordre",36:"Feu clic per obtenir traduccions alternatives",37:"Manteniu premuda la tecla de maj\u00fascules, feu clic a les paraules i arrossegueu-les per canviar l'ordre.",38:"Gr\u00e0cies per proposar una traducci\u00f3 al Traductor de Google.",39:"Gestiona la traducci\u00f3 d'aquest lloc",40:"Feu clic en una paraula per veure'n traduccions alternatives o b\u00e9 feu-hi doble clic per editar-la directament",41:"Text original",42:"Traductor",43:"Tradueix",
44:"S'ha enviat la vostra correcci\u00f3.",45:"Error: l'idioma de la p\u00e0gina web no \u00e9s compatible.",46:"Widget del men\u00fa d'idiomes del Traductor"};var n;function p(a,l){this.a=l===q?a:""}var q={};var r=window.google&&google.translate&&google.translate._const;
if(r){var t;a:{for(var u=[],v=[""],w=0;w<v.length;++w){var x=v[w].split(","),y=x[0];if(y){var z=Number(x[1]);if(!(!z||.1<z||0>z)){var A=Number(x[2]),B=new Date,C=1E4*B.getFullYear()+100*(B.getMonth()+1)+B.getDate();!A||A<C||u.push({version:y,ratio:z,b:A})}}}var D=0,E=window.location.href.match(/google\.translate\.element\.random=([\d\.]+)/),F=Number(E&&E[1])||Math.random();for(w=0;w<u.length;++w){var G=u[w];D+=G.ratio;if(1<=D)break;if(F<D){t=G.version;break a}}t="TE_20201130_00"}var H="/element/%s/e/js/element/element_main.js".replace("%s",
t);if("0"==t){var I=" element %s e js element element_main.js".split(" ");I[I.length-1]="main_ca.js";H=I.join("/").replace("%s",t)}if(r._cjlc)r._cjlc(r._pas+r._pah+H);else{var J=r._pas+r._pah+H,K,L="SCRIPT",M=document;L=String(L);"application/xhtml+xml"===M.contentType&&(L=L.toLowerCase());K=M.createElement(L);K.type="text/javascript";K.charset="UTF-8";var N,O;if(void 0===n){var P=null,Q=c.trustedTypes;if(Q&&Q.createPolicy){try{P=Q.createPolicy("goog#html",{createHTML:k,createScript:k,createScriptURL:k})}catch(a){c.console&&
c.console.error(a.message)}n=P}else n=P}var R=(O=n)?O.createScriptURL(J):J;N=new p(R,q);K.src=N instanceof p&&N.constructor===p?N.a:"type_error:TrustedResourceUrl";var S;var T=K.ownerDocument&&K.ownerDocument.defaultView;T&&T!=c?S=h(T.document):(null===g&&(g=h(c.document)),S=g);S&&K.setAttribute("nonce",S);var U=document.getElementsByTagName("head")[0];U||(U=document.body.parentNode.appendChild(document.createElement("head")));U.appendChild(K)}e("google.translate.m",m);e("google.translate.v",t)};}).call(window)
